- name: Configure SFTP Server
  hosts: managed_nodes
  become: true
  vars_files:
    - vars/users.yml
  roles:
    - system_setup  # Handles package installation, SSHD config, logging
    - users  # Creates groups, users, and sets permissions
