- name: Privision Ubuntu EC2 Instance
  hosts: localhost
  gather_facts: false
  tasks:

    # - name: Get latest Ubuntu AMI
    #   amazon.aws.ec2_ami_info:
    #     filters:
    #       image-id: "ami-00c257e12d6828491"
    #   register: ubuntu_ami

    # - name: Set AMI ID as a fact
    #   ansible.builtin.set_fact:
    #     aws_ami: "{{ ubuntu_ami.images | sort(attribute='creation_date') | last | default('ami-0c55b159cbfafe1f0') }}"

    - name: Load AWS variables
      ansible.builtin.include_vars:
        file: vars/aws.yml

    - name: Launch an EC2 instance
      amazon.aws.ec2_instance:
        name: "SFTP-Server"
        key_name: "{{ aws_sftp_key }}"
        instance_type: "t2.micro"
        security_groups: ["sg-01f8982579faa99e9"]
        image_id: "ami-00c257e12d6828491"
        region: "us-west-2"
        count: 1
        network:
          assign_public_ip: true
      register: ec2_result

    - name: Wait for instance to be accessible
      ansible.builtin.wait_for:
        host: "{{ ec2_result.instances[0].public_ip_address }}"
        port: 22
        delay: 30
        timeout: 300

    - name: Add new isntance to Ansible inventory
      ansible.builtin.add_host:
        name: "{{ ec2_result.instances[0].public_ip_address }}"
        groups: sftp_server
        ansible_user: ubuntu

    - name: Display instance details
      ansible.builtin.debug:
        msg: "EC2 instance is running at {{ ec2_result.instances[0].public_ip_address }}"
