- name: Privision Ubuntu EC2 Instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load AWS variables
      ansible.builtin.include_vars:
        file: vars/aws.yml

    - name: Check if an EC2 instance already Exists
      amazon.aws.ec2_instance_info:
        region: "us-west-2"
        filters:
          "tag:Name": "SFTP-Server"
          "instance-state-name": "running"
      register: existing_instance

    - name: Launch an EC2 instance (if none exists)
      amazon.aws.ec2_instance:
        name: "SFTP-Server"
        key_name: "{{ aws_sftp_key }}"
        instance_type: "t2.micro"
        security_groups: ["sg-01f8982579faa99e9"]
        image_id: "ami-00c257e12d6828491"
        region: "us-west-2"
        count: 1
        network:
          assign_public_ip: true
      register: ec2_result
      when: existing_instance.instances | length == 0

    - name: Determine instance details (existing or new)
      ansible.builtin.set_fact:
        instance_public_ip: >-
          {{ existing_instance.instances[0].public_ip_address if existing_instance.instances | length > 0 else ec2_result.instances[0].public_ip_address }}

    - name: Wait for instance to be accessible
      ansible.builtin.wait_for:
        host: "{{ instance_public_ip }}"
        port: 22
        delay: 30
        timeout: 300

    - name: Store instance IP in inventory.ini
      ansible.builtin.blockinfile:
        path: inventory.ini
        block: |
          [managed_nodes]
          {{ instance_public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/AnsibleController.pem
        create: true
        mode: '0600'

    - name: Display instance details
      ansible.builtin.debug:
        msg: "EC2 instance is running at {{ instance_public_ip }}"
